import functools
from typing import cast
import importlib.resources
import astropy.units as u
import astropy.time
import astropy.table
import aiapy.calibrate
import aiapy.calibrate.utils
import aiapy.response
import named_arrays as na

__all__ = [
    "temperature_response",
]

_file = "aia_V10_temperature_response.ecsv"
"""
The SolarSoft temperature response of every EUV channel, as shipped with
this package, and generated by ``tools/aia_temperature_response.py``.
"""


@functools.cache
def _table() -> astropy.table.QTable:
    """The table in :data:`_file`, read once."""
    path = importlib.resources.files("sdo.aia") / "data" / _file
    with importlib.resources.as_file(path) as file:
        return astropy.table.QTable.read(file, format="ascii.ecsv")


@functools.cache
def _correction_table() -> astropy.table.QTable:
    """
    The version 10 table of the time-dependent corrections, which is the one
    ``aia_get_response`` uses, fetched once from SolarSoft and cached by
    :mod:`aiapy`.
    """
    return aiapy.calibrate.utils.get_correction_table("SSW")


def temperature_response(
    wavelength: u.Quantity | na.AbstractScalar = [94, 131, 171, 193, 211, 335] * u.AA,
    time: None | str | astropy.time.Time = None,
    eve: bool = False,
    chiantifix: bool = False,
    axis_wavelength: str = "wavelength",
    axis_temperature: str = "temperature",
    correction_table: None | astropy.table.QTable = None,
) -> na.FunctionArray[na.ScalarArray, na.ScalarArray]:
    r"""
    The temperature response of the AIA EUV channels, as SolarSoft computes it.

    This is the response returned by ``aia_get_response(/temperature, /dn)``
    in the SolarSoft ``sdo/aia`` package, version 10 :cite:p:`Boerner2012`,
    which is the response most of the literature on AIA uses. It is the
    CHIANTI emissivity distributed with SolarSoft folded with the effective
    area of each channel, including the crosstalk between the channels which
    share a telescope. The keywords of this function correspond to the
    optional corrections of ``aia_get_response``.

    Parameters
    ----------
    wavelength
        The channels to return the response of.
        Must be among 94, 131, 171, 193, 211, 304 and 335 angstroms.
        If a :class:`~astropy.units.Quantity`, its channels are put along
        `axis_wavelength`.
    time
        If not :obj:`None`, the time to correct the response for the
        degradation of the instrument at, from the correction table
        :func:`aiapy.calibrate.degradation` reads. This is ``timedepend_date``
        in ``aia_get_response``. If :obj:`None` (the default), the response is
        that at the start of the mission, which should be compared with
        observations that have been corrected for degradation separately.
    eve
        Whether to normalize the response to agree with the irradiance
        measured by SDO/EVE, ``/evenorm`` in ``aia_get_response``. SolarSoft
        recommends this together with `time`.
    chiantifix
        Whether to add the empirical correction for emission missing from
        CHIANTI, ``/chiantifix`` in ``aia_get_response``. In this version only
        the 94 angstrom channel has a correction. It was derived for the
        EVE-normalized response, so it requires `eve`.
    axis_wavelength
        The name of the axis along the channels, if `wavelength` does not
        already have one.
    axis_temperature
        The name of the axis along the temperatures of the result.
    correction_table
        The table of the degradation and EVE normalization of each channel.
        If :obj:`None` (the default), the version 10 table SolarSoft uses is
        fetched with :func:`aiapy.calibrate.utils.get_correction_table`, if
        `time` or `eve` need it.

    Returns
    -------
    A function of temperature whose outputs are the response of each channel
    to unit emission measure, in
    :math:`\text{DN}\,\text{cm}^5\,\text{s}^{-1}\,\text{pix}^{-1}`. The emission
    measure is that of :math:`n_e n_H`, the convention of CHIANTI.

    Notes
    -----
    The table this function reads was computed from the version 9 effective
    area and emissivity files of SolarSoft, which version 10 still uses: CHIANTI
    9.0.1 with the coronal abundances of Feldman (1992) at a constant pressure
    of :math:`10^{15}\,\text{K}\,\text{cm}^{-3}`, at log temperatures from 4 to
    9 in steps of 0.05. It reproduces the output of ``aia_get_response`` in IDL
    to about one part in :math:`10^8`, and to one part in :math:`10^6` with the
    EVE normalization.

    The corrections are scalars per channel, so they are applied here as
    ``aia_get_response`` applies them:

    .. math::

        R(T, t) = \left[ R_0(T) \, C_E + R_\text{fix}(T) \right] C_T(t)

    where :math:`R_0` is the uncorrected response, :math:`C_E` is the EVE
    normalization, :math:`R_\text{fix}` is the empirical correction to
    CHIANTI, and :math:`C_T` is the degradation at time :math:`t`.

    Examples
    --------
    The response of the six channels used for DEMs at the start of the
    mission, and as ``aia_get_response(/temp, /dn, /evenorm,
    timedepend_date=...)`` gives it on a later date.

    .. jupyter-execute::

        import matplotlib.pyplot as plt
        import astropy.units as u
        import astropy.visualization
        import named_arrays as na
        import sdo

        channels = [94, 131, 171, 193, 211, 335]

        response = sdo.aia.temperature_response(channels * u.AA)
        response_2024 = sdo.aia.temperature_response(
            wavelength=channels * u.AA,
            time="2024-05-10",
            eve=True,
        )

        colors = [f"C{i}" for i in range(len(channels))]

        with astropy.visualization.quantity_support():
            fig, ax = plt.subplots(constrained_layout=True)
            na.plt.plot(
                response.inputs,
                response.outputs,
                ax=ax,
                axis="temperature",
                color=colors,
                label=[f"{c} Å" for c in channels],
            )
            na.plt.plot(
                response_2024.inputs,
                response_2024.outputs,
                ax=ax,
                axis="temperature",
                color=colors,
                linestyle="--",
            )
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.set_ylim(1e-28, 1e-23)
            ax.legend(title="dashed: 2024-05-10")
    """
    if chiantifix and not eve:
        raise ValueError("`chiantifix` was derived for the EVE-normalized response")

    if not isinstance(wavelength, na.AbstractArray):
        wavelength = u.Quantity(wavelength).reshape(-1)
        wavelength = na.ScalarArray(wavelength, axes=axis_wavelength)
    wavelength = cast(na.ScalarArray, wavelength.explicit)
    if not wavelength.shape:
        wavelength = wavelength.add_axes(axis_wavelength)
    if wavelength.ndim != 1:
        raise ValueError(f"`wavelength` must be 0D or 1D, got {wavelength.shape=}")
    (axis_wavelength,) = wavelength.shape

    table = _table()
    available = table.meta["channels"]

    channels = [
        int(round(w)) for w in u.Quantity(wavelength.ndarray).to_value(u.AA).reshape(-1)
    ]
    for channel in channels:
        if channel not in available:
            raise ValueError(
                f"AIA has no EUV channel at {channel} angstroms, the channels "
                f"are {available}"
            )

    if (time is not None or eve) and correction_table is None:
        correction_table = _correction_table()
    if time is not None:
        time = astropy.time.Time(time)

    responses = []
    for channel in channels:
        response = table[f"response_{channel}"]
        if eve:
            # computed at the time `aia_get_response` would compute it at:
            # the date of the correction, or now if there is none
            aia = aiapy.response.Channel(channel * u.AA)
            t = astropy.time.Time.now() if time is None else time
            response = response * aia.eve_correction(t, correction_table)
        if chiantifix:
            response = response + table[f"chiantifix_{channel}"]
        if time is not None:
            response = response * aiapy.calibrate.degradation(
                channel=channel * u.AA,
                obstime=time,
                correction_table=correction_table,
            )
        responses.append(response)

    return na.FunctionArray(
        inputs=na.ScalarArray(table["temperature"], axes=axis_temperature),
        outputs=na.ScalarArray(
            ndarray=u.Quantity(responses).T,
            axes=(axis_temperature, axis_wavelength),
        ),
    )
