import functools
from typing import Literal, cast
import importlib.resources
import astropy.units as u
import astropy.time
import astropy.table
import aiapy.calibrate
import aiapy.calibrate.utils
import aiapy.response
import named_arrays as na

__all__ = [
    "temperature_response",
]

_files = {
    "SolarSoft": "aia_V10_temperature_response.ecsv",
    "CHIANTI 11": "aia_chianti11_temperature_response.ecsv",
}
"""
The temperature response of every EUV channel for each emissivity, as shipped
with this package. The SolarSoft table is generated by
``tools/aia_temperature_response.py``, and the CHIANTI 11 table by
``tools/aia_temperature_response_chianti.py``.
"""

_version = 10
"""
The version of the calibration of SolarSoft the tables in :data:`_files`
belong to, and so the version of the corrections applied to them. Both use
the effective areas of this version.
"""


@functools.cache
def _table(emissivity: str) -> astropy.table.QTable:
    """The table of an emissivity in :data:`_files`, read once."""
    path = importlib.resources.files("sdo.aia") / "data" / _files[emissivity]
    with importlib.resources.as_file(path) as file:
        return astropy.table.QTable.read(file, format="ascii.ecsv")


@functools.cache
def _correction_table() -> astropy.table.QTable:
    """
    The version 10 table of the time-dependent corrections, which is the one
    ``aia_get_response`` uses, fetched once from SolarSoft and cached by
    :mod:`aiapy`.
    """
    return aiapy.calibrate.utils.get_correction_table("SSW")


@functools.cache
def _channel(channel: int) -> aiapy.response.Channel:
    """
    The instrument data :mod:`aiapy` has for a channel, which takes almost
    half a second to read, read once.
    """
    return aiapy.response.Channel(channel * u.AA)


def temperature_response(
    wavelength: u.Quantity | na.AbstractScalar = [94, 131, 171, 193, 211, 335] * u.AA,
    time: None | str | astropy.time.Time = None,
    eve: bool = False,
    chiantifix: bool = False,
    axis_wavelength: str = "wavelength",
    axis_temperature: str = "temperature",
    correction_table: None | astropy.table.QTable = None,
    emissivity: Literal["SolarSoft", "CHIANTI 11"] = "SolarSoft",
) -> na.FunctionArray[na.ScalarArray, na.ScalarArray]:
    r"""
    The temperature response of the AIA EUV channels, as SolarSoft computes it,
    or from version 11 of CHIANTI.

    By default, this is the response returned by
    ``aia_get_response(/temperature, /dn)`` in the SolarSoft ``sdo/aia``
    package, version 10 :cite:p:`Boerner2012`, which is the response most of
    the literature on AIA uses. It is the CHIANTI emissivity distributed with
    SolarSoft folded with the effective area of each channel, including the
    crosstalk between the channels which share a telescope. The keywords of
    this function correspond to the optional corrections of
    ``aia_get_response``.

    With ``emissivity="CHIANTI 11"``, the emissivity is instead computed from
    version 11 of CHIANTI :cite:p:`Dufresne2024`, with everything else as
    SolarSoft has it, so that the two responses differ by the atomic data
    alone.

    Parameters
    ----------
    wavelength
        The channels to return the response of.
        Must be among 94, 131, 171, 193, 211, 304 and 335 angstroms.
        If a :class:`~astropy.units.Quantity`, its channels are put along
        `axis_wavelength`.
    time
        If not :obj:`None`, the single time to correct the response for the
        degradation of the instrument at, from the correction table
        :func:`aiapy.calibrate.degradation` reads. This is ``timedepend_date``
        in ``aia_get_response``. If :obj:`None` (the default), the response is
        that at the start of the mission, which should be compared with
        observations that have been corrected for degradation separately.
    eve
        Whether to normalize the response to agree with the irradiance
        measured by SDO/EVE, ``/evenorm`` in ``aia_get_response``. SolarSoft
        recommends this together with `time`. Without `time`, the
        normalization is that of the first epoch of the correction table,
        where ``aia_get_response`` uses that of the current date. Every epoch
        of version 10 has the same normalization.
    chiantifix
        Whether to add the empirical correction for emission missing from
        CHIANTI, ``/chiantifix`` in ``aia_get_response``. In this version only
        the 94 angstrom channel has a correction. It was derived for the
        EVE-normalized response, so it requires `eve`: without it this
        function raises an error, where ``aia_get_response`` turns on
        ``/evenorm`` itself. It corrects the emissivity of SolarSoft, so it
        is an error with any other `emissivity`.
    axis_wavelength
        The name of the axis along the channels, if `wavelength` does not
        already have one.
    axis_temperature
        The name of the axis along the temperatures of the result.
    correction_table
        The table of the degradation and EVE normalization of each channel.
        If :obj:`None` (the default), the version 10 table SolarSoft uses is
        fetched with :func:`aiapy.calibrate.utils.get_correction_table`, if
        `time` or `eve` need it. Only the rows of version 10 are used, since
        that is the version of the response, so a table of every version,
        like the one :mod:`aiapy` fetches from the JSOC, gives the same
        result, and a table without version 10 is an error.
    emissivity
        The emission of the plasma the response is computed from.
        ``"SolarSoft"`` (the default) is the CHIANTI 9 emissivity of version
        10 of SolarSoft. ``"CHIANTI 11"`` is computed from version 11 of
        CHIANTI, its lines and continua and its ionization equilibrium, with
        the abundances, pressure, and empirical boost of the He II 304
        angstrom line of SolarSoft. The effective areas, and so `time` and
        `eve`, are the same for both.

    Returns
    -------
    A function of temperature whose outputs are the response of each channel
    to unit emission measure, in
    :math:`\text{DN}\,\text{cm}^5\,\text{s}^{-1}\,\text{pix}^{-1}`. The emission
    measure is that of :math:`n_e n_H`, the convention of CHIANTI.

    Notes
    -----
    The SolarSoft table this function reads was computed from the version 9
    effective area and emissivity files of SolarSoft, which version 10 still
    uses: CHIANTI 9.0.1 with the coronal abundances of Feldman (1992) at a
    constant pressure of :math:`10^{15}\,\text{K}\,\text{cm}^{-3}`, at log
    temperatures from 4 to 9 in steps of 0.05. It reproduces the output of
    ``aia_get_response`` in IDL to about one part in :math:`10^8`, and to one
    part in :math:`10^6` with the EVE normalization.

    The CHIANTI 11 table was computed from CHIANTI 11.0.2 with :mod:`fiasco`
    :cite:p:`Barnes2026` and :mod:`utu`, folded with the same effective areas
    on the same temperatures. It sums every line at its own wavelength, where
    SolarSoft first bins the lines into steps of 0.1 angstroms, dropping in the
    process the lines which fall exactly halfway between two steps, like the
    O V line at 192.750 angstroms.

    The largest difference between the two is in the 94 angstrom channel,
    whose response from CHIANTI 11 is a quarter of that of SolarSoft at
    log T 6.35. Most of the response of SolarSoft there is the
    :math:`3s^2\,3d\,^2D_{3/2} - 3s^2\,4p\,^2P_{1/2}` line of Fe XIV, which
    CHIANTI 9 put at 93.61 angstroms and CHIANTI 11 moved out of the channel
    to 91.27 angstroms, following :cite:t:`Lepson2023`. The empirical
    correction of `chiantifix` adds emission at these temperatures to the
    response of SolarSoft, and there is no such correction for CHIANTI 11.

    The corrections are scalars per channel, so they are applied here as
    ``aia_get_response`` applies them:

    .. math::

        R(T, t) = \left[ R_0(T) \, C_E + R_\text{fix}(T) \right] C_T(t)

    where :math:`R_0` is the uncorrected response, :math:`C_E` is the EVE
    normalization, :math:`R_\text{fix}` is the empirical correction to
    CHIANTI, and :math:`C_T` is the degradation at time :math:`t`.

    Examples
    --------
    The response of the six channels used for DEMs at the start of the
    mission, and as ``aia_get_response(/temp, /dn, /evenorm,
    timedepend_date=...)`` gives it on a later date.

    .. jupyter-execute::

        import numpy as np
        import matplotlib.pyplot as plt
        import astropy.units as u
        import astropy.visualization
        import named_arrays as na
        import sdo

        channels = [94, 131, 171, 193, 211, 335]

        response = sdo.aia.temperature_response(channels * u.AA)
        response_2024 = sdo.aia.temperature_response(
            wavelength=channels * u.AA,
            time="2024-05-10",
            eve=True,
        )

        # a color and a label for each channel, along the axis of channels
        colors = na.ScalarArray(
            ndarray=np.array([f"C{i}" for i in range(len(channels))]),
            axes="wavelength",
        )
        labels = na.ScalarArray(
            ndarray=np.array([f"{c} Å" for c in channels]),
            axes="wavelength",
        )

        with astropy.visualization.quantity_support():
            fig, ax = plt.subplots(constrained_layout=True)
            na.plt.plot(
                response.inputs,
                response.outputs,
                ax=ax,
                axis="temperature",
                color=colors,
                label=labels,
            )
            na.plt.plot(
                response_2024.inputs,
                response_2024.outputs,
                ax=ax,
                axis="temperature",
                color=colors,
                linestyle="--",
            )
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.set_ylim(1e-28, 1e-23)
            ax.legend(title="dashed: 2024-05-10")

    The ratio of the response from CHIANTI 11 to that of SolarSoft, where the
    SolarSoft response is at least a hundredth of its peak.

    .. jupyter-execute::

        response_11 = sdo.aia.temperature_response(
            wavelength=channels * u.AA,
            emissivity="CHIANTI 11",
        )

        ratio = response_11.outputs / response.outputs
        peak = response.outputs.max(axis="temperature")
        ratio = np.where(response.outputs > peak / 100, ratio, np.nan)

        with astropy.visualization.quantity_support():
            fig, ax = plt.subplots(constrained_layout=True)
            na.plt.plot(
                response.inputs,
                ratio,
                ax=ax,
                axis="temperature",
                color=colors,
                label=labels,
            )
            ax.axhline(1, color="black", linewidth=0.5)
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.set_ylabel("CHIANTI 11 / SolarSoft")
            ax.legend()
    """
    if emissivity not in _files:
        raise ValueError(
            f"`emissivity` must be one of {list(_files)}, got {emissivity!r}"
        )
    if chiantifix and emissivity != "SolarSoft":
        raise ValueError("`chiantifix` corrects the emissivity of SolarSoft only")
    if chiantifix and not eve:
        raise ValueError("`chiantifix` was derived for the EVE-normalized response")

    if not isinstance(wavelength, na.AbstractArray):
        wavelength = u.Quantity(wavelength).reshape(-1)
        wavelength = na.ScalarArray(wavelength, axes=axis_wavelength)
    wavelength = cast(na.ScalarArray, wavelength.explicit)
    if not wavelength.shape:
        wavelength = wavelength.add_axes(axis_wavelength)
    if wavelength.ndim != 1:
        raise ValueError(f"`wavelength` must be 0D or 1D, got {wavelength.shape=}")
    (axis_wavelength,) = wavelength.shape

    table = _table(emissivity)
    available = table.meta["channels"]

    channels = [
        int(round(w)) for w in u.Quantity(wavelength.ndarray).to_value(u.AA).reshape(-1)
    ]
    for channel in channels:
        if channel not in available:
            raise ValueError(
                f"AIA has no EUV channel at {channel} angstroms, the channels "
                f"are {available}"
            )

    if (time is not None or eve) and correction_table is None:
        correction_table = _correction_table()
    if correction_table is not None:
        version = correction_table["VER_NUM"] == _version
        if not version.any():
            raise ValueError(
                f"`correction_table` has no rows of version {_version}, "
                f"the version of the response"
            )
        correction_table = correction_table[version]
    if time is not None:
        time = astropy.time.Time(time)
        if time.shape:
            raise ValueError(f"`time` must be a single time, got {time.shape=}")

    responses = []
    for channel in channels:
        response = na.ScalarArray(table[f"response_{channel}"], axes=axis_temperature)
        if eve:
            # Without a time, at the start of the first epoch, since every
            # epoch has the same normalization. `aia_get_response` uses the
            # current date, which falls in no epoch once the last one ends.
            t = time
            if t is None:
                t = astropy.time.Time(correction_table["T_START"].min())
            response = response * _channel(channel).eve_correction(t, correction_table)
        if chiantifix:
            fix = table[f"chiantifix_{channel}"]
            response = response + na.ScalarArray(fix, axes=axis_temperature)
        if time is not None:
            response = response * aiapy.calibrate.degradation(
                channel=channel * u.AA,
                obstime=time,
                correction_table=correction_table,
            )
        responses.append(response)

    return na.FunctionArray(
        inputs=na.ScalarArray(table["temperature"].copy(), axes=axis_temperature),
        outputs=na.stack(responses, axis=axis_wavelength),
    )
